from django.core.management.base import BaseCommand
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.conf import settings
from django.db import models
from inventory.models import Category, InventoryItem
from django.db.models import Prefetch

class Command(BaseCommand):
    help = "Sends full inventory report email with low-stock highlights"

    def handle(self, *args, **options):
        EXCLUDED_PRODUCT_NAMES = [
            "3D Motion Display Panel",
            "3d Printer Sapre Lever",
            "3 Shape Clear Aligner Studio",
            "3 Shape Design Studio",
            "3 Shape Implant Studio",
            "3Shape Ortho Suite EDU - Single Seat",
            "3 Shape Splint Studio",
            "3 Shape Studio Suite",
            "3shape studio suite 100 Cases",
            "3 Shape Studio Suite Educational Software",
            "3 Shape Studio Suite Edu - Single Seat",
            "3 Shape trios 3 adaptor",
            "3 Shape Trios 3 Move Intraoral Scanner",
            "3 Shape trios 3 scanning tips.",
            "5XTRIM BELT",
            "Ackudent Guide Resin",
            "Ackudent Model Resin (Ivory)",
            "Ackudent Model Resin (Light Beige)",
            "Ackudent Temporary Resin",
            "Ackuretta Mini Heater",
            "Ackuretta Sol Print Screen",
            "Ackuretta Sol Resin Tray",
            "Ackuretta SOL - Vat Assembly with Vat BoxVat Assembly with Vat Box",
            "Aligner Box With Mirror",
            "Aligner Retriever",
            "Aligner Trimming Machine",
            "Anycubic",
            "Anycubic Abs Like Pro 2 Black Color",
            "Anycubic Abs Like Pro 2 Grey Color",
            "Anycubic Beige Model Resin",
            "Anycubic Beige Resin",
            "Anycubic Cleaning and Curing Machine 2.0",
            "Anycubic Green Resin",
            "Anycubic (Grey)",
            "Anycubic (Grey) (D)",
            "Anycubic (Light Beige)",
            "Anycubic m7 max ACF sheet pack of 5",
            "Anycubic Mono 2 Lcd",
            "Anycubic Photon Mono -2 Fep Sheets(Pack Of 2)",
            "Anycubic Resin",
            "Anycubic Resin Skin",
            "Anycubic Tough Resin Ultra Grey",
            "Anycubic Wash and Cure 3",
            "Anycubic Wash & Cure Plus",
            "Anycubic Water Wash Resin+ Beige",
            "Anycubic Water Wash Resin+ Black",
            "Anycubic Water Wash Resin + Clear",
            "Anycubic Water Wash Resin+ GREY",
            "Asiga 5Kg Vat",
            "Asiga Max Uv 10 Kg Resin Tray",
            "Asiga Max Uv 1Kg Resin Tray",
            "Asiga Max Uv 2Kg Resin Tray",
            "Asiga Max Uv 5Kg Resin Tray",
            "Asiga Model Resin",
            "Bambu Lab A1 3D Printer Combo(with AMS lite)",
            "Bambu Lab A1 3-D Printers",
            "bambu lab a1 build plate",
            "Bambu Lab Hotend Nozzle",
            "Bambu Lab P1S 3D Printer",
            "Bambu Lab P1S Combo (With AMS) 3D Printer",
            "Bambu Lab X1 Carbon Combo 3D Printer",
            "Blocking Out Wax 50G",
            "Ceramage 4.6G (2.6Ml) Gum",
            "Chef 3 Pcs Set",
            "Chewies For Aligners",
            "C I Motion Erkopress",
            "Conical Polisher Bur",
            "Connecter",
            "Cover Templates 110 900",
            "Curo",
            "Curo ProCast 500g",
            "Cylinder",
            "DC POWER Adaptor",
            "Dental Silicone Polishers",
            "Dental Studio Ortho Studio Configuration",
            "Dental Ultrasonic Cleaner 14 Ltr",
            "Dentiq Lcd Screen(Pack of 3 )",
            "Dento Optiprint Guide 385 Clear 1kg",
            "Dtech 3D Accuprint C&B Pro Resin A2 Shade 500G",
            "Dtech 3D Accuprint C&B Resin A1 Shade 500G",
            "Dtech 3D Accuprint C&B Resin A2 Shade 500G",
            "Dtech 3D Accuprint C&B Resin B1 Shade 500G",
            "D-Tech 3 D Accuprint Model Hard Grey Resin",
            "D-Tech 3 D Accuprint Model Hard Ivory Resin",
            "D-Tech, 3D Accuprint Sugical Guide 500 Gm (Sample)",
            "D-tech, 3D Accuprint Surgical Guide 500Gm",
            "Dtech Accuprint C&B Resin A2 Shade 500G",
            "D-tech, Custom Tray 500 gm",
            "D-Tech Custom Tray Resin 500 Gm",
            "D-Tech Hard Splint Resin 500g",
            "D-TECH HARD SPLINT RESIN 500gm",
            "D-Tech Model Pro Beige",
            "D-Tech Pro Glaze 5ml",
            "D- Tech temp crown resin A2 Shade 500gms",
            "Duran+ Clear 0.625mm 100/pk",
            "Duran+Clear 120mm 1.0 10/pk",
            "Dust Cover",
            "Dust Suction",
            "E2 Lab Scanner",
            "Eco Trim Box",
            "Elegoo Castable Resin Green 500g",
            "Elegoo Centurai Carbon 3D Printer",
            "Elegoo Jupiter Se",
            "Elegoo Jupiter SE PFA film*5pcs",
            "elegoo lcd for saturn 3 ultra 12k",
            "Elegoo Mars 5 Ultra",
            "ELEGOO MATTE PLA Filament 1.75mm Matte White 1 kg",
            "ELEGOO Mercury XS Bundle Washing and Curing Station",
            "Elegoo Mercury Xs Wash And Cure Unit",
            "Elegoo Neptune 4 Max Hotend Nozzel",
            "Elegoo Nepture 4 Max",
            "Elegoo Nfep Sheets",
            "Elegoo Saturn 4 Ultra",
            "Elegoo PFA Release Liner Film (5Pcs)",
            "Elegoo PLA+ Filament_x000D_ 1.75mm Translucent",
            "Elegoo PLA+ Filament 1.75mm Black",
            "ElegooPLA+ Filament 1.75mm Silver",
            "Elegoo PLA Grey Beginner-friendly PLA in Grey",
            "Elegoo PLA Neon GREEN Beginner-friendly PLA",
            "Elegoo PLA Orang beginner-friendly PLA in Orange",
            "Elegoo Rapid PLA+ Filament 1.75mm Black",
            "Elegoo Rapid PLA+ Filament 1.75mm Grey",
            "Elegoo Rapid PLA+ Filament 1.75mm Silver",
            "Elegoo Rapid PLA+ Filament 1.75mm Translucent",
            "Elegoo Resin Vat",
            "Elegoo Saturn 1 PFA Flim (5 Pcs)",
            "Elegoo Saturn 2 8K",
            "Elegoo Saturn 2 LCD Screen",
            "Elegoo Saturn 2 Ultra Lcd Screen",
            "Elegoo Saturn 3 Ultra ACF Film",
            "Elegoo Saturn 3 Ultra Build Platform",
            "Elegoo Saturn 3 Ultra Lcd Screen",
            "Elegoo Saturn 3 Ultra Pfa Flim (5 Pcs)",
            "Elegoo Saturn 3 Ultra Resin 3D Printer With 12K Mono Lcd",
            "Elegoo Saturn 4 Lcd",
            "Elegoo Saturn 4 Ultra 12K FEP Film (Pack of 5)",
            "Elegoo Saturn 4 Ultra 16k ACF Film (Pack of 5)",
            "Elegoo Saturn 4 Ultra Lcd Screen",
            "Elegoo Saturn 4 Ultra PFA Flim (5 Pcs)",
            "Elegoo Saturn 8K Acf Sheet",
            "Elegoo Saturn Ultra 3",
            "ELEGOO STANDARD UV RESIN - GRAY",
            "ELEGOO TPU 1.75mm Filament – Flexible, Durable & Print-Ready",
            "Elego Saturn 3 Ultra Resin 3d Printer 12k",
            "Envisiontec, E-Model Light",
            "Envision Tec Psa Tray Vida",
            "Envisiontec Vida Psa",
            "Envisiontec Vida Vat (Medium)",
            "Erkodent,Erkodur-0M, 1.00 mm, Ø 120 mm, tooth colour",
            "Erkodent, Erkodur-0M1, 0.60 Mm, Ø 120 Mm, Tooth Colour",
            "Erkodent, Erkodur-0M1, 1.00 Mm, Ø 120 Mm, Tooth Colour",
            "Erkodent,Erkodur -S 0.8x 120",
            "Erkodent, Erkoform 3D Motion(18)",
            "Erkodent, Erkopress Ci Lcd Pannel",
            "Erkodent, Erkopress C I Motion Compressor",
            "Erkodent, Erkopress ci_ motion",
            "Erkodent, Erkopress Motion Themforming Machines",
            "Erkodent, FG",
            "Erkodent Foil Reception & Foil Securing Ring",
            "Erkodur 0.8 x 125",
            "Erkodur 4.0 x 125 (1)",
            "Erkodur Al 0.8 x 125",
            "Erkoflex 1.0 X120 (1)",
            "Erkoflex 4.00 mm, 120 mm, Free Style (Rainbow)",
            "Erkoflex 95 2.5mm, 120mm Clear",
            "Erkolen 0.6 x 125",
            "Erkoloc Pro 1.0 x 120 (1)",
            "Erkoloc Pro 1.0 X125 (1)",
            "Erkoloc Pro 3.00 120mm",
            "Eroflex bleach 1.0mm, 125mm",
            "Filling Granules 1.3 Kg",
            "Filling Granules Rounded, High- Grade Steel",
            "Fine Cross Cut Carbide Bur",
            "Fissure Bur (Pack of 2)",
            "Guided Mold Pot Erkopress Motion",
            "HP ZBOOK",
            "H S S Twist Drill 1 MM",
            "HYBRID SHEET 3MM,125MM",
            "LisKOSIL S( PAck of 100)",
            "Mighty 4k Up Down Motor",
            "Mighty 8k Nfep",
            "Mini 8K LCD",
            "Phrozen ACF Release Film- mini(pack of 3)",
            "Mini 8ks LCD",
            "Mini 8k Vat",
            "Mini Star Thermoforming Machine",
            "MOON RESIN CASTABLE PURPLE",
            "Moon Resin - Model Standard",
            "New Futron 3",
            "Occluform-3(18)",
            "Ortho Studio - Basic Configuration",
            "Ortho Suit Edu Software",
            "Oxy Regulator",
            "pacdent rodin sculpture 2.0 A2 shade 600g",
            "Pacdent Rodin Titan Resin A1 Shade 600gm",
            "PFA FEP Release Film for Mars 4/ 5/ 5 Ultra (5 Pcs)",
            "Phrozen 3d Printer Sonic Mini 8ks",
            "Phrozen, 9.3\" 4K Mono-Lcd Panel For Sonic Mighty 4K",
            "Phrozen ABS like 3D (matte gray)",
            "Phrozen ACF Release Film- mega 8k (pack of 3)",
            "Phrozen ACF Release Film- mega 8ks",
            "Phrozen ACF Release Film- mega 8ks (pack of 3)",
            "Phrozen ACF Release Film- mighty(pack of 3)",
            "Phrozen Aqua 8k Snow Gray Resin",
            "Phrozen Aqua Hyperfine 3D Printing Resin- 1 kg graphite",
            "Phrozen Cure V2",
            "PHROZEN MEGA 8K",
            "Phrozen Mega 8k Lcd",
            "PHROZEN MEGA 8KS",
            "PHROZEN MEGA 8KS NFEP SHEET (Pack of 3)",
            "PHROZEN MEGA CURE S",
            "PHROZEN MEGA WASH S",
            "PHROZEN MIGHTY 4K",
            "Phrozen Mighty 4k Vat",
            "Phrozen Mighty 8k",
            "Phrozen Mighty 8k NFEP",
            "Phrozen Mini 4k",
            "Phrozen Mini 8ks",
            "Phrozen Mini 8ks Resin Vat",
            "Phrozen PFA(NFEP) A3 for Sonic Mega 8K",
            "Phrozen Resin 8k",
            "Phrozen Revo Nfep",
            "Phrozen Sonic Mega 8k S",
            "Phrozen Sonic Mighty Revo 14k 3d printer",
            "Phrozen Sonic Mighty Revo 16 k 3d printer",
            "Phrozen Sonic Mighty Revo Vat",
            "Phrozen TR300 Ultra-High Temp 3D Printer Resin",
            "PHROZEN WASH AND CURE KIT",
            "PHROZEN WATER WASHABLE RESIN GREY",
            "Play Safe Bite Spacer",
            "Play safe Face Chuck",
            "Playsafe Triple Single Colour",
            "Playsafe Triple Various Colours (Sample)",
            "Play Triple Set",
            "Play Triple Set (1)",
            "Power Adapter-Sprit Pod PSU-24V 30W",
            "POWERCAST BURN RESIN (500GM)",
            "POWERCAST DARK ZERO RESIN 1KG",
            "Powercast Yellow Resin",
            "Print Screen for SOL (Pack of 2)",
            "PRO GLAZE 5 ML (1)",
            "Pump & Fill For Mega 8KS",
            "RASIN WAX-LIKE VIOLET 500GM",
            "Renfort Blocking Out wax",
            "Resin tank of Formslab 4B",
            "Resin Tray Of Elegoo Saturn 4 ultra 16k",
            "Retriever",
            "Rodin titan C&B B1 shade 600gm",
            "Round Polishing Bur",
            "SAMPLE BOX WITH INSERT",
            "S C 801 Resin",
            "Screw (Build Platform)",
            "Service Charges",
            "SIRAYA TECH CASTABLE True Blue Resin",
            "Siraya Tech Uv Resin Cast Blue",
            "Siraya Tech Uv Resin Cast Purple",
            "Siriya Tech Fast ABS Resin Navy Grey",
            "Sol Vat",
            "SS.JAGUAR JUG 6LTR",
            "STATIONERY EXP",
            "STATIONERY EXP.12",
            "Sunlu ABS-Like Resin - 1 kg gray",
            "sunlu abs like white resin",
            "Tiffany 2pcs Set",
            "Trios 3 Color Pod Pen Special Configuration",
            "Trios 3 Power adapter",
            "Trios 3 special configuration scanner",
            "Tungsten Carbide Bur Conical",
            "TWP4K093 BOARD",
            "Universal Opaque Wo 2ml",
            "VAT ASSEMBLY WITH VAT BOX",
            "Wow Mini Meal 2pcs Set",
            "3 Shape Trios 3 2024 Intra Oral Scanner",
            "3 Shape Trios 3 Wired Intra Oral Scanner",
            "3 Shape Trios Basic Intra Oral Scanner",
            "5Xtrim Aligner Trimming",
            "5Xtrim Cam (Software)",
            "5Xtrim Quick Swap Plate",
            "5Xtrim trimming bur 2mm dia (Pack of 5)",
            "Ackudent Model Resin (Grey)",
            "Ackuretta Cleani With Dual Tank",
            "Ackuretta Curo c&b A1 Shade Resin 500G",
            "Ackuretta Curo Guide Resin 500G",
            "Ackuretta Curo Model Element Resin 500G",
            "Ackuretta Curo ProDenture Light Pink 500gm",
            "Ackuretta curo pro gingival resin500g",
            "Ackuretta Curo ProSplint 500g",
            "Anycubic Uv Resin (Black)",
            "Anycubic Uv Resin (Clear)",
            "Aqua 4K Gray Resin",
            "Aqua Resin Grey 5 Kgs",
            "Aqua Resin Ivory 5 Kgs",
            "Elegoo Saturn 4 Ultra 16K",
            "Elegoo Washing and cure",
            "Erkodent,Erkodur-A1, 0.60 mm, Ø 120 mm, tooth colour",
            "Erkodent,Erkodur-A1, 1.00 mm, Ø 120 mm, tooth colour",
            "Erkodent,Erkodur-A2, 1.00 mm, Ø 120 mm, tooth colour",
            "Erkodent,Erkodur-A2, 1.5mm 120mm, tooth colour",
            "Erkodent,Erkodur-A2, 2.00 mm, Ø 120 mm, tooth colour",
            "Erkodent,Erkodur-A3, 1.00 mm, Ø 120 mm, tooth colour",
            "Erkodent, Erkoflex Playsafe Triple Foil Transparent",
            "Erkodent, Erkopress 240",
            "Erkodent Sealing Ring for Presspot",
            "Fissure Bur Rightward Cutting Left Spiral",
            "FORM 4B 3D PRINTER",
            "Form 4B Basic Package ( with OMM )",
            "Form 4B Complete Package ( with OMM )",
            "Form labs Denture Base Resin",
            "Form labs Fast model resin",
            "Graphy Resin Ta 28",
            "Hot Air Burner With Acc",
            "LCD OF Phrozen Sonic Mighty 8k",
            "Lisko-B",
            "Lisko Polishing Discs Assorted",
            "LISKO SET",
            "Liskosil -L",
            "Liskosil M",
            "Liskosil -S",
            "Lisko-S Polishing Discs",
            "Maestro 3D Dental Studio Expert Ortho Studio Basic Software Update",
            "Maestro V6 Orthostudio Basic",
            "Maestro V7 Orthostudio Basic",
            "Magnetic Aligner Box With Silicon Base",
            "Magnetic Aligner Box With Silicon Base with mirror",
            "NFINITY",
            "Occ3-4p",
            "Occluform-3",
            "Phrozen Aqua 4k Grey",
            "Phrozen Aqua 8K Gray",
            "Phrozen Aqua Ivory",
            "Polishing Bur",
            "SILENSOR SI",
            "SILENSOR-SI PART CARD",
            "Silensor-Si Parts With Protrutision Guage",
            "Slim Aligner Box",
            "Slim Box",
            "Special scissors",
            "UltraSonic Cleaner",
            "Ultrasonic Cleaner 4.5 Ltr",
            "Uniz NBEE Build Platform",
            "Uniz platform",
            "Uniz UBEE 3D Printer",
            "Zendura A 1mm x 125 Dia",
            "Zendura FLX 0.76mm 125mm (Pack of 10)",
            "Zendura FLX 0.76 X 120 MM (AL)",
            "ZENDURA FLX 0.76 X 120 SAMPLE",
            "Zendura FLX 0.76 x 125MM",
            "Zendura FLX 0.76 x 125 (Pack of 10)",
            "Zendura Trak 0.38mmx 125mm (Pack of 10 Sheets)",
            "Zendura Trak 0.38mm x 125 mm( Pack of 30 )",
            "Zendura Trak 0.38 x 125",
            "ZENDURA TRAK 0.38 X 125 SAMPLE",
            "Mini 8K NFEP",
            "Phrozen ACF Release Film- mega 8k (pack of 3)",
            "Magnetic Aligner Box With Silicon Base with Mirror",
            "3Shape Ortho Suite EDU - Single Seat",
            "Ackuretta Curo Model Element Beige 1 Kg",
            "Ackuretta Curie Plus",
            "Ackuretta Curie",
            "Ackuretta Curo ProDenture Light Pink 500gm",
            "Ackuretta Curo ProSplint 500gram",
            "Dentiq Lcd Screen",
            "Ackuretta SOL - Vat Assembly with Vat BoxVat Assembly with Vat Box",
            "Ackuretta Curie Plus Top Cover",
            "SOL BUILD PLATFORM LARGE",
            "Ackuretta Dentiq",
            "Erkodent,Erkodur, 1.50 mm, Ø 125 mm, clear",
            "Erkodent,Erkodur, 4.00 mm, Ø 120 mm, clear",
            "Erkodent,Erkoflex, 1.50 mm, Ø 120 mm, transparent",
            "Erkodent,Erkoflex, 3.00 mm, Ø 120 mm, transparent",
            "Erkodent,Erkoflex, 4.00 mm, Ø 120 mm, Night Blue",
            "Erkodent,Erkoflex-bleach, 1.00 mm, Ø 125 mm, transparent",
            "Erkodent, Erkogum Blocking Out Material",
            "Erkoloc Pro 1.0 x 120 (1)",
            "Erkodent,Erkoloc-pro, 2.00mm, Ø 125 Ø 125 mm, transparent",
            "Erkodent,Erkoloc-pro, 2.00mm, Ø 125 Ø 125 mm, Blue",
            "Erkodent,Erkoloc-pro, 2.00mm, Ø 125 Ø 125 mm, Green",
            "Erkodent,Erkoflex 4.00 mm, Ø 120 mm, Pure White",
            "Anycubic m7 max ACF sheet pack of 5",
            "Zendura FLX 0.76 x 125 (Pack of 01)",
            "Erkoflex-95, 4.00 mm, Ø 125 mm, transparent",
            "Erkodent,Erkodur, 0.80 mm, Ø 240 mm, clear",
            "Erkodent,Erkodur al, 0.80 mm, Ø 240 mm, transparent",
            "Phrozen Standard TR250 LV Deep Gray Resin",
            "Bambu Lab P1S Combo (With AMS) 3D Printer",
            "Bambu Lab H2D 3D Printer (Without AMS)",
            "Finishing Set Quick 3",
            "Finishing Set",
            "Uniformation Wash 3 Ultra",
            "Phrozen cure v 2 with ultrasonic cleaner",
            "Dtech 3D Accuprint C&B Resin A1 Shade 500G",
            "Dtech Model Standard",
            "Dtech 3D Accuprint C&B Resin B1 Shade 500G",
            "D-Tech Custom Tray Resin 500 Gm",
            "D-tech Standard Model Resin Tray",
            "Elegoo Saturn 2 8K",
            "Elegoo Saturn 4k",
            "Elegoo Saturn Ultra 3",
            "ELEGOO NEPTUNE 4 MAX",
            "ELEGOO Neptune 4 plus",
            "Elegoo Saturn 4 12k",
            "Elegoo Saturn 3 ultra",
            "elegoo lcd for saturn 3 ultra 12k",
            "Elegoo Saturn 1 PFA Flim (5 Pcs)",
            "Elegoo PLA+ Filament  1.75mm Translucent",
            "ELEGOO MATTE PLA Filament 1.75mm Sakura Pink",
            "ELEGOO Silk PLA Filament 1.75mm Red",
            "Mercury Plus V3.0 wash and cure station",
            "Envisiontec Vida Psa",
            "Spare Part- Steel Spring",
            "Foil Securing Ring Erkopress",
            "LCD -DISPLAY 3D MOTION",
            "Formlabs, Form 4B Basic Package",
            "Formlabs, Form 4B Complete Package (With OMM )",
            "Formlabs Open Material Mode(OMM) License Upgradation",
            "Formlabs Grey V5 5 ltr can (For Form 4)",
            "Resin Pump (Form 4) Maintenance Kit",
            "Phrozen Sonic Mega 8k V2",
            "Uniformation GK3 Ultra- 16K resolution",
            "Pacdent Rodin Titan C&B [600g] A1 Shade",
            "Pacdent Rodin Sculpture 2.0 C&B 600g A1 shade",
            "Sunlu ABS-Like Resin GRAY",
            "Sunlu standard black resin",
            "Draft Resin (Cartridgev2)RS-F2-DRDR-02",
            "Draft Resin (Form 3) RS-RPS -DRGR-02 5 Ltr",
            "Fast Model Resin 5Ltr",
            "Fast Model Resin 1 Ltr",
            "compressor 1 hp",
            "Resin Tank of Formlab 3 RT- F3-02-01",
            "Resin Pump (Form 4)",
            "Kevin Peter smile 2 scanner",
            "Jacket",
            "Jacket (L)",
            "Jacket (M)",
            "Jacket (S)",
            "Jacket (XL)",
            "Jacket (XXL)",
            "ELEGOO RAPID PLA+ Filament 1.75mm Gray",
            "Slimline 2 Door",
            "TALLY SUBSCRIPTION",
            "Exocad Core",
            "Exocad Unlimited Bundle",
            "O-Ring",
            "ANYCUBIC 3D PRINTER PHOTON MONO 4",
            "Jamghe Eco Resin Grey",
            "Jamghe Eco Stand Resin Almond",
            "Jamghe Eco Resin Skin",
            "jamghe resin beige",
            "Pacdent N2 Free Palette Naturalization Kit"
        ]

        # 🧾 Get all categories with related inventory items
        categories = Category.objects.prefetch_related(
            Prefetch(
                'inventoryitem_set',
                queryset=InventoryItem.objects.exclude(
                    name__in=EXCLUDED_PRODUCT_NAMES
                )
            )
        ).all()

        if not any(c.inventoryitem_set.exists() for c in categories):
            self.stdout.write(self.style.WARNING("⚠️ No inventory items found."))
            return

        # 🧮 Identify low stock items
        low_stock_items = InventoryItem.objects.exclude(
            name__in=EXCLUDED_PRODUCT_NAMES
        ).filter(
            quantity__lt=models.F('min_quantity_outwards')
        )

        # 📦 Prepare context for email template
        context = {
            "categories": categories,
            "low_stock_items": low_stock_items,
        }

        # 🧩 Render HTML email content
        html_content = render_to_string('inventory/low_stock_email.html', context)

        # ✉️ Prepare email
        subject = "📊 Daily Inventory Report (Low Stock Alerts Included)"
        from_email = getattr(settings, 'DEFAULT_FROM_EMAIL', None)
        # to_emails = ["nitin.a@obluhc.com","swasti.obluhc@gmail.com","accounts@obluhc.com","sanyam.obluhc@gmail.com","sujal.obluhc@gmail.com","raman.obluhc@gmail.com","vibhuti.obluhc@gmail.com"]  # 👈 your target email
        to_emails=["madderladder68@gmail.com","swasti.obluhc@gmail.com","sanyam.obluhc@gmail.com"]
        msg = EmailMultiAlternatives(subject, "", from_email, to_emails)
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        self.stdout.write(self.style.SUCCESS("✅ Inventory report email sent to madderladder68@gmail.com"))
